### ISSUE TITLE
Possibility to add a civit ai api key in order to have access to more models 

### ISSUE THREAD

**Issue by Arrrlinks** [civitai/comfy-nodes#14]
I can't get some models because we need to be connected to civitai, there should be a option in the node to add a civitai api key

**Comment by Ainaemaet** [comment]
Yup, second this notion - for those of us who use models that need API there is currently no way to get them with the nodes provided here as you just get a 401

**Comment by saadkhan955** [comment]
same here

```
[CivitAI] Downloading `Dhevv-OctopusConcept.safetensors` from `[https://civitai.com/api/download/models/314165`](https://civitai.com/api/download/models/314165%60)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/comfy-nodes/civitai_lora_loader.py", line 91, in load_lora
    if not civitai_model.download():
  File "/workspace/ComfyUI/custom_nodes/comfy-nodes/CivitAI_Model.py", line 313, in download
    raise Exception(f"{ERR_PREFIX}Failed to download {self.type} file from CivitAI. Status code: {response.status_code}")
Exception: [CivitAI] Error: Failed to download LORA file from CivitAI. Status code: 401
```

**Comment by youngeuibae** [comment]
same herer

**Comment by webcoderz** [comment]
this fork works, https://github.com/Arrrlinks/civitai_comfy_nodes theres an active PR with it that seems to function correctly

update.. this fork is missing the api_key=None in the lora loader, i forked and added until its merged  in:
https://github.com/webcoderz/civitai_comfy_nodes

**Comment by larinius** [comment]
How possible to code all that node things and not implement the first thing ever for any API - Auth token ?

**Comment by webcoderz** [comment]
> How possible to code all that node things and not implement the first thing ever for any API - Auth token ?

Use my fork above

**Comment by WASasquatch** [comment]
> i forked and added until its merged in:

Do you intend to make a PR, then?

**Comment by webcoderz** [comment]
> > i forked and added until its merged in:
> 
> Do you intend to make a PR, then?

yea good idea https://github.com/civitai/civitai_comfy_nodes/pull/18
